/*Cursor que indique por cada cliente cuantas veces ha estado en el hotel sin promoción y con promoción.*/
DO $$
DECLARE
	REGISTRO RECORD;
	CUR_VISITAS CURSOR FOR 
		SELECT
		SIN.CLIENTE,
		SIN.SIN_PROMO,
		CON.CON_PROMO
		FROM
		/*CONSULTA CON PROMO*/
		(
			select 
			CONCAT(CLIENTE.CLIENTE_NOMBRE, ' ', CLIENTE.CLIENTE_APELLIDO) AS CLIENTE,
			COUNT(FACTURA.FACTURA_ID) AS CON_PROMO
			FROM CLIENTE
				LEFT JOIN FACTURA ON FACTURA.CLIENTE_ID=CLIENTE.CLIENTE_ID 
				AND FACTURA.DESCUENTO_ID <> 0
			GROUP BY CLIENTE
		)AS CON
		FULL JOIN 
		/*CONSULTA SIN PROMO*/
		(
			select 
			CONCAT(CLIENTE.CLIENTE_NOMBRE, ' ', CLIENTE.CLIENTE_APELLIDO) AS CLIENTE,
			COUNT(FACTURA.FACTURA_ID) AS SIN_PROMO
			FROM CLIENTE
				LEFT JOIN FACTURA ON FACTURA.CLIENTE_ID=CLIENTE.CLIENTE_ID 
				AND FACTURA.DESCUENTO_ID = 0
			GROUP BY CLIENTE
		) AS SIN
		ON SIN.CLIENTE=CON.CLIENTE;

BEGIN
FOR REGISTRO IN CUR_VISITAS LOOP
	RAISE NOTICE 'EL CLIENTE: % HA VISITADO EL HOTEL % VECES CON PROMO Y % VECES SIN PROMO',
	REGISTRO.CLIENTE,REGISTRO.CON_PROMO, REGISTRO.SIN_PROMO;
END LOOP ;
END $$
LANGUAGE 'plpgsql';
	