/*Procedimiento almacenado que muestre en cuantas habitaciones ha estado un cliente al consultar su nombre.*/
CREATE OR REPLACE FUNCTION BUSCAR(IN nombre varchar,OUT total_habitacion varchar)
as 
$$
begin 
/*ESTA CONSULTA DEVUELVE LA CANTIDAD DE HABITACIONES EN LA QUE HA ESTADO UN CLIENTE*/
/*DE HABER ESTADO EN LA MISMA HABITACION VARIAS VECES SOLO SE CONTARA UNA VEZ*/
	SELECT 
	COUNT (DISTINCT HABITACION.HABITACION_NUMERO) INTO total_habitacion
	FROM CLIENTE
	INNER JOIN FACTURA ON FACTURA.CLIENTE_ID=CLIENTE.CLIENTE_ID
	INNER JOIN HABITACION ON HABITACION.HABITACION_ID=FACTURA.HABITACION_ID
	WHERE CLIENTE.CLIENTE_NOMBRE=NOMBRE;
end
$$
language 'plpgsql';

SELECT * FROM BUSCAR('GABRIELA');
SELECT * FROM BUSCAR('CHANYEOL');

